name: Run Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install pipenv
      run: pip install pipenv
    
    - name: Install dependencies
      run: pipenv sync --dev
    
    - name: Run tests
      run: pipenv run ./bin/test